# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Samuel Littley
tagline:             'Passionate about programming and theatre'
description:         'The alternative home of Samuel Littley on the Web.'
url:                 http://samuellittley.me
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Samuel Littley
  url:               http://samuellittley.me
  email:             samuel@samuellittley.me

# Custom vars
version:             1.0.0
